version: '3'
services:
  mosquitto:
    hostname: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    volumes:
      - c:\mosquitto\mosquitto.conf:\mosquitto\config\mosquitto.conf
      - c:\mosquitto\mosquitto.passwd:\mosquitto\config\mosquitto.passwd
      - c:\mosquitto\log\mosquitto.log:\mosquitto\log\mosquitto.log
      - c:\mosquitto\data:\mosquitto\data
    ports:
      - "1883:1883"
      - "9001:9001"